@startuml TP5_Punto_1
title Punto 1 - Pasaporte, Foto, Titular

package Ejercicio1 {
  class Pasaporte {
    -numero : String
    -fechaEmision : String
  }
  class Foto {
    -imagen : String
    -formato : String
  }
  class Titular {
    -nombre : String
    -dni : String
  }

  Pasaporte "1" *-- "1" Foto : composicion
  Pasaporte "1" -- "1" Titular : asociacion bidireccional
}
@enduml
